routes/api_user.py
from flask import (
    redirect,
    Blueprint,
    request,
    session,
    url_for,
)

from utils import log
from models.user import User

main = Blueprint('user_api', __name__)


@main.route('/login', methods=['POST'])
def login():
    """
    登录页面的路由函数
    """
    log('login, cookies', request.cookies)
    form = request.form
    u = User.new(form)
    if u.validate_login():
        u = User.find_by(username=u.username)
        session['user_id'] = u.id
        log('session', session)
        # 登录后定向到 /
        return redirect(url_for('static.index'))
    else:
        return redirect(url_for('user.login'))


@main.route('/register', methods=['POST'])
def register():
    """
    注册页面的路由函数
    """
    form = request.form
    u = User.new(form)
    if u.validate_register():
        # 注册成功再保存
        u.save()
        # 注册成功后 定向到登录页面
        return redirect(url_for('user.login'))
    else:
        # 注册失败 定向到注册页面
        return redirect(url_for('user.register'))

routes/routes_todo.py
from flask import (
    render_template,
    Blueprint,
)
from routes import login_required

# 创建一个蓝图对象
# 路由都定义在蓝图对象中
# 然后再 flask 主代码中 注册蓝图 来使用
# 第一个参数是蓝图的名字 以后会有用
# 第二个参数是套路

main = Blueprint('todo', __name__)


@main.route('/index')
@login_required
def index():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('todo_index.html')

routes/routes_weibo.py
from flask import (
    render_template,
    Blueprint,
)

from routes import login_required

main = Blueprint('weibo', __name__)


# 微博相关页面
@main.route('/index')
@login_required
def index():
    return render_template('weibo_index.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>吃瓜主页</title>
</head>
<body>
    <h1>Hello {{username}}</h1>
    <img src="{{ url_for('static', filename='doge.gif') }}"/>
    <img src="{{ url_for('static', filename='doge1.jpg') }}"/>
    <img src="{{ url_for('static', filename='doge2.gif') }}"/>
    <br>
    <a href="{{ url_for('user.login') }}">Login</a>
    <a href="{{ url_for('user.register') }}">Register</a>
    <a href="{{ url_for('todo.index') }}">Todo</a>
    <a href="{{ url_for('weibo.index') }}">Weibo</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册登录页面</title>
</head>
<body>
    <h1>登录</h1>
    <h2>你好 {{username}}</h2>
    <form action="{{ url_for('user_api.login') }}" method="post">
        <input type="text" name="username" placeholder="请输入用户名">
        <br>
        <input type="text" name="password" placeholder="请输入密码">
        <br>
        <button type="submit">登录</button>
    </form>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
    <h1>注册</h1>
    <form action="{{ url_for('user_api.register') }}" method="post">
        <input type="text" name="username" placeholder="请输入用户名">
        <br>
        <input type="text" name="password" placeholder="请输入密码">
        <br>
        <button type="submit">注册</button>
    </form>
</body>
</html>

templates/todo_index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>AJAX  Flask  Todo </title>

         <style  type="text/css">

        .button-success,
        .button-error,
        .button-warning,
        .button-secondary {
            color: white;
            border-radius: 4px;
            text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
        }

        .button-success {
            background: rgb(28, 184, 65); /* this is a green */
        }

        .button-error {
            background: rgb(202, 60, 60); /* this is a maroon */
        }

        .button-warning {
            background: rgb(223, 117, 20); /* this is an orange */
        }

        .button-secondary {
            background: rgb(66, 184, 221); /* this is a light blue */
        }

        </style>
    </head>
    <body>
        <h1 class="gua-center">TODO List</h1>
        <br>
        <div class="gua-center">
            <input id='id-input-todo' class="pure-form" placeholder="Write TODO">
            <button id='id-button-add' class="button-small pure-button pure-button-primary">添加</button>
        </div>
        <br>
        <table class="pure-table pure-table-bordered gua-center-block">
            <thead>
                <tr>
                    <th>TODO</th>
                    <th>Create Time</th>
                    <th>编辑</th>
                    <th>删除</th>
                 </tr>
            </thead>
            <tbody id="id-todo-list">

            </tbody>
        </table>

        <!-- 这是我们处理静态文件的套路 -->
        <!-- gua.js 放了公共的函数 -->
        <!-- 按顺序引入 2 个 js 文件, 后面的 js 文件就能使用前面的文件中的函数了 -->
        <script src="{{ url_for('static', filename='gua.js') }}"></script>
        <script src="{{ url_for('static', filename='todo.js') }}"></script>
    </body>


    <!-- 引用外部 CSS -->
    <link href="{{ url_for('static', filename='pure.css')  }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='gua.css') }}" rel="stylesheet">
</html>

templates/weibo_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weibo ajax</title>
    <style>
        .comment {
            border: 1px red solid;
        }
    </style>
</head>
<body>
    <h1 class="gua-center">微博</h1>

    <div class="gua-center">
        <input id='id-input-weibo' class="pure-form">
        <button id='id-button-add' class="button-small pure-button pure-button-primary">添加</button>
    </div>

    <div class="gua-center">
        <table>
            <thead>
                <tr>
                    <th>微博</th>
                    <th>编辑</th>
                    <th>删除</th>
                    <th>添加评论</th>
                 </tr>
            </thead>
            <tbody id="id-weibo-list">

            </tbody>

        </table>

    </div>
    <!-- 这是我们处理静态文件的套路 -->
    <!-- gua.js 放了公共的函数 -->
    <!-- 按顺序引入 2 个 js 文件, 后面的 js 文件就能使用前面的文件中的函数了 -->
    <script src="{{ url_for('static', filename='gua.js') }}"></script>
    <script src="{{ url_for('static', filename='weibo.js') }}"></script>
    <script src="{{ url_for('static', filename='comment.js') }}"></script>
</body>
    <!-- 引用外部 CSS -->
    <link href="{{ url_for('static', filename='pure.css')  }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='gua.css') }}" rel="stylesheet">
</html>